"use client";

import { useEffect, useState } from "react";
import { Plus, Send, Trash2, X } from "lucide-react";

type Meter = { energy_type:"electricite"|"gaz"; identifier:string; contract_expiry:string; address:string; postal_code:string; city:string };
const emptyMeter=(energy_type:Meter["energy_type"]="electricite"):Meter=>({energy_type,identifier:"",contract_expiry:"",address:"",postal_code:"",city:""});

export type AcdProspectPrefill={id:string;raison_sociale:string|null;siren:string|null;siret:string|null;company_address:string|null;company_postal_code:string|null;company_city:string|null;prenom:string|null;nom:string|null;mail:string|null;telephone:string|null;pdl:string|null;pce:string|null;meters:Array<{type_energie:"electricite"|"gaz";numero:string;date_echeance:string|null;adresse:string|null;code_postal:string|null;ville:string|null}>};

export function AcdRequestForm({prospect,hiddenTrigger=false,openImmediately=false}:{prospect:AcdProspectPrefill;hiddenTrigger?:boolean;openImmediately?:boolean}) {
  const savedMeters:Meter[]=prospect.meters.map(m=>({energy_type:m.type_energie,identifier:m.numero,contract_expiry:m.date_echeance??"",address:m.adresse??"",postal_code:m.code_postal??"",city:m.ville??""}));
  const defaults:Meter[]=savedMeters.length?savedMeters:[...(prospect.pdl?[{...emptyMeter("electricite"),identifier:prospect.pdl}]:[]),...(prospect.pce?[{...emptyMeter("gaz"),identifier:prospect.pce}]:[])];
  const [open,setOpen]=useState(openImmediately); const [saving,setSaving]=useState(false); const [error,setError]=useState<string|null>(null);
  const [meters,setMeters]=useState<Meter[]>(defaults.length?defaults:[emptyMeter()]);
  const updateMeter=(index:number,patch:Partial<Meter>)=>setMeters(rows=>rows.map((row,i)=>i===index?{...row,...patch}:row));
  useEffect(()=>{const openForm=()=>setOpen(true);window.addEventListener("open-acd-request",openForm);return()=>window.removeEventListener("open-acd-request",openForm)},[]);

  async function submit(event:React.FormEvent<HTMLFormElement>){
    event.preventDefault();setSaving(true);setError(null);const form=new FormData(event.currentTarget);
    const response=await fetch(`/api/acd/${prospect.id}/demander`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({raison_sociale:form.get("raison_sociale"),siren:form.get("siren"),siret:form.get("siret"),company_address:form.get("company_address"),company_postal_code:form.get("company_postal_code"),company_city:form.get("company_city"),signatory_first_name:form.get("signatory_first_name"),signatory_last_name:form.get("signatory_last_name"),signatory_email:form.get("signatory_email"),signatory_phone:form.get("signatory_phone"),signatory_capacity:form.get("signatory_capacity"),signatory_role:form.get("signatory_role"),notes:form.get("notes"),meters})});
    const data=await response.json().catch(()=>({})) as {error?:string};
    if(!response.ok){setError(data.error||"Envoi impossible.");setSaving(false);return;}
    window.location.href=`/prospection/${prospect.id}?acd=transmise`;
  }

  return <>
    {!hiddenTrigger?<button type="button" onClick={()=>setOpen(true)} className="inline-flex h-9 items-center justify-center rounded-xl bg-star-500 px-4 text-xs font-bold text-white hover:bg-star-600"><Send size={14} className="mr-2"/>Créer la demande d&apos;ACD</button>:null}
    {open?<div className="fixed inset-0 z-[100] flex items-start justify-center overflow-y-auto bg-navy-950/55 p-4 py-8"><div className="w-full max-w-4xl rounded-2xl bg-white shadow-2xl">
      <div className="flex items-start justify-between border-b border-navy-100 px-6 py-5"><div><h2 className="font-display text-xl font-bold text-navy-900">Demande d&apos;ACD</h2><p className="mt-1 text-sm text-grey-brand">Informations nécessaires pour Volto et YouSign.</p></div><button type="button" onClick={()=>setOpen(false)} className="rounded-lg p-2 text-navy-400 hover:bg-navy-50"><X size={20}/></button></div>
      <form onSubmit={submit} className="space-y-6 p-6">
        <div className="rounded-xl border border-star-200 bg-star-50 px-4 py-3 text-sm font-semibold text-navy-800">Tous les champs marqués * sont obligatoires. La demande ne peut pas être envoyée tant qu&apos;une information manque.</div>
        <section><h3 className="text-sm font-bold text-navy-800">Entreprise</h3><div className="mt-3 grid gap-3 md:grid-cols-3"><Field name="raison_sociale" label="Raison sociale *" required defaultValue={prospect.raison_sociale}/><Field name="siren" label="SIREN (9 chiffres) *" required defaultValue={prospect.siren} pattern="[0-9]{9}"/><Field name="siret" label="SIRET (14 chiffres) *" required defaultValue={prospect.siret} pattern="[0-9]{14}"/><Field name="company_address" label="Adresse du siège *" required defaultValue={prospect.company_address}/><Field name="company_postal_code" label="Code postal *" required defaultValue={prospect.company_postal_code} pattern="[0-9]{5}"/><Field name="company_city" label="Ville *" required defaultValue={prospect.company_city}/></div></section>
        <section><h3 className="text-sm font-bold text-navy-800">Signataire</h3><div className="mt-3 grid gap-3 md:grid-cols-2"><Field name="signatory_first_name" label="Prénom" required defaultValue={prospect.prenom}/><Field name="signatory_last_name" label="Nom" required defaultValue={prospect.nom}/><Field name="signatory_email" label="E-mail" type="email" required defaultValue={prospect.mail}/><Field name="signatory_phone" label="Téléphone" required defaultValue={prospect.telephone}/><label className="text-xs font-semibold text-navy-600">Qualité du signataire<select name="signatory_capacity" required className="mt-1.5 h-10 w-full rounded-xl border border-navy-200 bg-white px-3 text-sm text-navy-900"><option value="representant_legal">Représentant légal</option><option value="mandataire">Mandataire</option></select></label><Field name="signatory_role" label="Fonction / statut (gérant, président…)" required/></div></section>
        <section><div className="flex items-center justify-between"><div><h3 className="text-sm font-bold text-navy-800">Compteurs et échéances</h3><p className="mt-1 text-xs text-grey-brand">Une ligne par PDL ou PCE.</p></div><button type="button" onClick={()=>setMeters(rows=>[...rows,emptyMeter()])} className="inline-flex items-center rounded-lg border border-navy-200 px-3 py-2 text-xs font-bold text-navy-700 hover:bg-navy-50"><Plus size={14} className="mr-1"/>Ajouter</button></div>
          <div className="mt-3 space-y-3">{meters.map((meter,index)=><div key={index} className="grid gap-3 rounded-xl border border-navy-100 bg-navy-50/40 p-3 md:grid-cols-2 lg:grid-cols-[120px_1fr_150px_1.4fr_110px_1fr_44px]"><label className="text-xs font-semibold text-navy-600">Énergie *<select required value={meter.energy_type} onChange={e=>updateMeter(index,{energy_type:e.target.value as Meter["energy_type"]})} className="mt-1.5 h-10 w-full rounded-xl border border-navy-200 bg-white px-3 text-sm"><option value="electricite">Électricité</option><option value="gaz">Gaz</option></select></label><label className="text-xs font-semibold text-navy-600">{meter.energy_type==="electricite"?"PDL":"PCE"} (14 chiffres) *<input required pattern="[0-9]{14}" value={meter.identifier} onChange={e=>updateMeter(index,{identifier:e.target.value.replace(/\D/g,"").slice(0,14)})} className="mt-1.5 h-10 w-full rounded-xl border border-navy-200 bg-white px-3 text-sm"/></label><label className="text-xs font-semibold text-navy-600">Échéance *<input required type="date" value={meter.contract_expiry} onChange={e=>updateMeter(index,{contract_expiry:e.target.value})} className="mt-1.5 h-10 w-full rounded-xl border border-navy-200 bg-white px-3 text-sm"/></label><label className="text-xs font-semibold text-navy-600">Adresse du compteur *<input required value={meter.address} onChange={e=>updateMeter(index,{address:e.target.value})} className="mt-1.5 h-10 w-full rounded-xl border border-navy-200 bg-white px-3 text-sm"/></label><label className="text-xs font-semibold text-navy-600">Code postal *<input required pattern="[0-9]{5}" value={meter.postal_code} onChange={e=>updateMeter(index,{postal_code:e.target.value.replace(/\D/g,"").slice(0,5)})} className="mt-1.5 h-10 w-full rounded-xl border border-navy-200 bg-white px-3 text-sm"/></label><label className="text-xs font-semibold text-navy-600">Ville *<input required value={meter.city} onChange={e=>updateMeter(index,{city:e.target.value})} className="mt-1.5 h-10 w-full rounded-xl border border-navy-200 bg-white px-3 text-sm"/></label><button type="button" disabled={meters.length===1} onClick={()=>setMeters(rows=>rows.filter((_,i)=>i!==index))} className="mt-6 flex h-10 items-center justify-center rounded-xl text-red-500 hover:bg-red-50 disabled:opacity-30"><Trash2 size={16}/></button></div>)}</div>
        </section>
        <label className="block text-xs font-semibold text-navy-600">Note pour l&apos;administrateur<textarea name="notes" rows={3} className="mt-1.5 w-full rounded-xl border border-navy-200 px-3 py-2 text-sm"/></label>
        {error?<div className="rounded-xl bg-red-50 px-4 py-3 text-sm font-medium text-red-700">{error}</div>:null}
        <div className="flex justify-end gap-2 border-t border-navy-100 pt-4"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border border-navy-200 px-4 py-2.5 text-sm font-semibold text-navy-700">Annuler</button><button disabled={saving} className="rounded-xl bg-star-500 px-5 py-2.5 text-sm font-bold text-white hover:bg-star-600 disabled:opacity-60">{saving?"Envoi…":"Envoyer la demande"}</button></div>
      </form>
    </div></div>:null}
  </>;
}

function Field({label,defaultValue,...props}:{label:string;defaultValue?:string|null}&Omit<React.InputHTMLAttributes<HTMLInputElement>,"defaultValue">){return <label className="text-xs font-semibold text-navy-600">{label}<input {...props} defaultValue={defaultValue??""} className="mt-1.5 h-10 w-full rounded-xl border border-navy-200 bg-white px-3 text-sm font-normal text-navy-900 outline-none focus:border-sky-capella-400 focus:ring-2 focus:ring-sky-capella-100"/></label>}
